language: rust
sudo: false

matrix:
  include:
    - rust: 1.30.0
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --all-features
        - cargo doc --all-features --no-deps -p auto_enumerate -p auto_enumerate_core -p auto_enumerate_derive
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test
        - cargo test --no-default-features
        - cargo test --all-features
        - cd "${TRAVIS_BUILD_DIR}/test_suite/tests_2018"
        - cargo test --all-features

before_script:
  - set -o errexit

script:
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/test_suite"
  - cargo test
  - cargo test --no-default-features

notifications:
  email: false
