language: rust
sudo: false
cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true

  allow_failures:
    - rust: nightly
      env: ALLOW_FAILURES=true

  include:
    - rust: 1.30.0
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --all-features
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test
        - cargo test --no-default-features
        - cargo test --all-features

    - rust: nightly
      name: cargo test (minimal versions)
      env: ALLOW_FAILURES=true
      script:
        - cargo update -Zminimal-versions
        - cargo test --all-features
        - cd "${TRAVIS_BUILD_DIR}/test_suite"
        - cargo test --all-features

    - rust: nightly
      name: cargo test (2018 edition)
      script:
        - cd "${TRAVIS_BUILD_DIR}/test_suite/tests_2018"
        - cargo test --all-features

    - rust: nightly
      name: cargo doc
      script:
        - cargo doc --all-features --no-deps -p auto_enums -p auto_enums_core -p auto_enums_derive

before_script:
  - set -o errexit

script:
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/test_suite"
  - cargo test
  - cargo test --no-default-features

notifications:
  email:
    on_success: never
